apiVersion: apps/v1
kind: Deployment
metadata:
  name: javademo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
      - name: javademo
        image: crpi-29ns4nxq5xxuk3v4.cn-hangzhou.personal.cr.aliyuncs.com/wenhegantian/javademo:IMAGE_TAG
        ports:
        - containerPort: 8080

